name: Flutter Build

on:
  push:
    branches: [ main ]  # Only build on main branch
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

env:
  FLUTTER_VERSION: '3.38.3'

# Add permissions at workflow level
permissions:
  contents: write  # This is crucial for creating releases
  actions: read
  checks: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor

    - name: Get dependencies
      run: flutter pub get

    - name: Build Android APK
      run: |
        flutter build apk --release --no-tree-shake-icons
      env:
        FLUTTER_BUILD_MODE: release

    - name: Build Android App Bundle
      run: |
        flutter build appbundle --release --no-tree-shake-icons
      env:
        FLUTTER_BUILD_MODE: release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Igalive-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: Igalive-appbundle
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main'  # Only create releases from main branch
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        body: |
          Automatic build triggered by ${{ github.event.head_commit.message }}
          
          Build includes:
          - Android APK
          - Android App Bundle
          - Built with --no-tree-shake-icons flag
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        
